---
title: "Q96 QC 2.0"
output: html_notebook
---

## Loading libraries and setting up directories 

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(lattice)
library(data.table)
library(jtools)
library(janitor)
library(vroom)
library(ggplot2)
library(viridis)
library(purrr)
library(stringr)

# Set up directories 
inputs <- paste0(getwd(), "/inputs/")
outputs <- paste0(getwd(), "/outputs/")
output_plots <- paste0(outputs, "plots/")
```

## Read in and consolidate run files 

```{r}

# Pointing to the directory containing the machine files
input_files <- list.files(paste0(inputs,"run_files/"))

# Import and clean colnames of each file
read_in <- function(path){
  vroom(path) %>% clean_names()}

machine_results_list <- list()

for (i in input_files){
  temp_reads <- read_in(paste0(inputs,"run_files/",i))
  temp_reads$plate <- i
  machine_results_list[[i]] <- temp_reads
}

methyl_table <- bind_rows(machine_results_list)
colnames(methyl_table)


methyl_table_cleaned <- methyl_table %>%
  rename(meth_901 = pos_1_methylation_percent,
         meth_924 = pos_2_methylation_percent,
         meth_934 = pos_3_methylation_percent) %>%
  select(sample_id, plate, well, 
         meth_901, meth_924, meth_934) %>%
  mutate(plate = str_replace(plate, ".txt", ""))

colnames(methyl_table_cleaned)

# Checking for sample name mismatches before proceeding
genolist <- vroom(paste0(inputs, "genolist.txt")) %>% clean_names()
name_checks <- filter(filter(methyl_table_cleaned, 
                             !sample_id %in% 
                               c("100%_MC", "NTC", "0%_MC", "50%_MC", 
                                 "100%_MC", "0% MC", "50% MC", "100% MC", 
                                 "BLANK")), 
                      !sample_id %in% genolist$sample)
name_checks


methyl_table_cleaned <- methyl_table_cleaned %>%
  mutate(sample_id = recode_factor(sample_id,
                                   "100% MC" = "100%_MC",
                                   "50% MC" = "50%_MC",
                                   "0% MC" = "0%_MC"))

nrow(filter(filter(methyl_table_cleaned, 
                             !sample_id %in% c("100%_MC", "NTC", "0%_MC", 
                                               "50%_MC", "100%_MC", "BLANK")), 
                      !sample_id %in% genolist$sample))

# 0, all good
```

## QC filtering 

The consolidated plate looks good. Now to generate the summary stats and push them into a new table that consolidates all three text files for each batch into one batch report per sample

```{r}

# QC across all batches

batches <- LETTERS[seq(from = 1, to = 11)]
post_qc_list <- list()

import_runfile <- function(file){
    vroom(file) %>% 
    clean_names() %>%
    select(well, sample_id, pos_1_methylation_percent, pos_2_methylation_percent,
           pos_3_methylation_percent) %>%
    rename("meth_901" = "pos_1_methylation_percent",
           "meth_924" = "pos_2_methylation_percent",
           "meth_934" = "pos_3_methylation_percent") %>%
    mutate(sample_id = recode_factor(sample_id,
                                   "100% MC" = "100%_MC",
                                   "50% MC" = "50%_MC",
                                   "0% MC" = "0%_MC"))
}

sd_correction <- function(samp, column_df){
  values <- filter(run_file, sample_id == samp)
  values <- values[, column_df]
  dif_1_2 <- as.numeric(abs(values[1,] - values[2,]))
  dif_1_3 <- as.numeric(abs(values[1,] - values[3,]))
  dif_2_3 <- as.numeric(abs(values[2,] - values[3,]))
  updated_mean <- ifelse(dif_1_2 < 5 & !is.na(dif_1_2), 
                         mean(as.numeric(values[1,]), as.numeric(values[2,])),
                  ifelse(dif_1_3 < 5 & !is.na(dif_1_3), 
                         mean(as.numeric(values[1,]), as.numeric(values[3,])),
                  ifelse(dif_2_3 < 5 & !is.na(dif_2_3), 
                         mean(as.numeric(values[2,]), as.numeric(values[3,])),
                                NA)))
  return(updated_mean)
}

```

## Running the QC pipeline

```{r}

passed_samples <- list()
failed_samples <- list()
z <- 1
batches <- LETTERS[seq(from = 1, to = 11)]
for(i in batches){
  # Each batch is composed of three plates (A-J, 1-3)
  # The output changes between 49 to 50 columns due to quirks of the machine
  # Importing each file then cleaning them up and binding together before generating summary stats
  # and flagging QC failures
  run_files <- list.files(paste0(inputs, "run_files"), 
                          pattern = paste0(i,".*"), full.names = TRUE)
  df_1 <- import_runfile(run_files[1])
  df_2 <- import_runfile(run_files[2])
  df_3 <- import_runfile(run_files[3])
  run_file <- bind_rows(df_1, df_2, df_3)
  run_file_summary <- run_file %>%
    group_by(sample_id) %>%
    summarize(mean_901 = mean(meth_901, na.rm = TRUE), sd_901 = sd(meth_901, na.rm = TRUE),
              mean_924 = mean(meth_924, na.rm = TRUE), sd_924 = sd(meth_924, na.rm = TRUE),
              mean_934 = mean(meth_934, na.rm = TRUE), sd_934 = sd(meth_934, na.rm = TRUE),
              na_count_901 = sum(is.na(meth_901)), na_count_924 = sum(is.na(meth_924)),
              na_count_934 = sum(is.na(meth_934)))
  run_file_summary <- run_file_summary %>%
    mutate(sd_flag_901 = ifelse(sd_901 > 5, "yes", "no")) %>%
    mutate(sd_flag_924 = ifelse(sd_924 > 5, "yes", "no")) %>%
    mutate(sd_flag_934 = ifelse(sd_934 > 5, "yes", "no")) %>%
    mutate(na_flag = ifelse(na_count_901 > 1 | 
                            na_count_924 > 1 | 
                            na_count_934 >1, 
                            "yes", "no")) %>%
    mutate(batch = as.character(i))
  
  # filter out any samples that have zero flags, classify as passed QC
  good_samples <- filter(run_file_summary, 
                         sd_flag_901 == "no" & sd_flag_924 == "no" &
                         sd_flag_934 == "no" & na_flag == "no")
  
  # filter out any samples that have an NA flag, obligate rerun
  bad_samples <- filter(run_file_summary,
                        na_flag == "yes")
  
  # Filter out any sample that has an SD flag but no NA flag, could still be good
  flagged_samples <- filter(run_file_summary,
                            (sd_flag_901 == "yes" | sd_flag_924 == "yes" |
                            sd_flag_934 == "yes") & na_flag == "no")
  
  # Apply the correction for each position to each sample, NA out the mean if
  # there are no two samples that are within 5% methylation of eachother
  flagged_samples <- flagged_samples %>%
    rowwise() %>%
    mutate(mean_901 = ifelse(sd_flag_901 == "yes", 
                             sd_correction(sample_id, "meth_901"),
                             mean_901)) %>%
    mutate(mean_924 = ifelse(sd_flag_924 == "yes", 
                             sd_correction(sample_id, "meth_924"),
                             mean_924)) %>%
    mutate(mean_934 = ifelse(sd_flag_934 == "yes", 
                             sd_correction(sample_id, "meth_934"),
                             mean_934))
  
  # Append the relevant lists and output results 
  good_samples <- bind_rows(good_samples, 
                            filter(flagged_samples,
                                   !is.na(mean_901) &
                                   !is.na(mean_924) &
                                   !is.na(mean_934)))
  bad_samples <- bind_rows(bad_samples,
                           filter(flagged_samples,
                                  is.na(mean_901) |
                                  is.na(mean_924) |
                                  is.na(mean_934))) %>%
    filter(sample_id != "NTC")

  passed_samples[[z]] <- good_samples
  failed_samples[[z]] <- bad_samples
  
z <- z + 1
}

passed_samples_df <- bind_rows(passed_samples)
failed_samples_df <- bind_rows(failed_samples)

rm(machine_results_list, methyl_table, methyl_table_cleaned, name_checks, post_qc_list, temp_reads, batches, i, input_files, bad_samples, df_1, df_2, df_3, failed_samples,
   flagged_samples, genolist, good_samples, passed_samples, run_file, run_file_summary)

write.table(passed_samples_df, 
            file = paste0(outputs, "20210202_Q96_QC_filtered_samples.txt"),
            sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)

write.table(failed_samples_df, 
            file = paste0(outputs, "20210202_Q96_failed_QC_samples.txt"),
            sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
```

